# =============================  AHAB recreated configuration from :06/02/2024 13:32:32.  ==============================

# ======================================================================================================================
#                                                 == General Options ==
# ======================================================================================================================
# ------------------------------------------===== MCU family [Required] =====-------------------------------------------
# Description: Family identifier including the chip revision. If revision is not present, latest revision is used as
# default.
# Possible options: <mimx8ulp, mimx9352, mimx9596, mimxrt1189>
family: mimx9352
# -----------------------------------------===== MCU revision [Optional] =====------------------------------------------
# Description: Revision of silicon
revision: a1
# ----------------------------------===== Target memory [Conditionally required] =====----------------------------------
# Description: Target memory for AHAB container
# Possible options: <nor, serial_downloader, nand_2k, nand_4k>
target_memory: serial_downloader
# ---------------------------------------===== Output file name [Required] =====----------------------------------------
# Description: Output AHAB file name
output: outputs/signed-u-boot-atf-container.img
# ------------------------------===== List of containers present in AHAB [Required] =====-------------------------------
# Description: The order of containers in the list defines the order in AHAB.
containers:
  - container:
      # --------------------------------===== Super Root Key (SRK) set [Required] =====---------------------------------
      # Description: Defines which set is used to authenticate the container.
      # Possible options: <none, oem, nxp>
      srk_set: oem
      used_srk_id: 0 # [Conditionally required], Used SRK, Which key from SRK set is being used.
      srk_revoke_mask: 0 # [Optional], SRK revoke mask, Bitmask to indicate which SRKs to revoke. Bit set to 1 means revoke key. Bit 0 = revoke SRK_0, bit 1 = revoke SRK_1 etc.
      # --------------------------------------===== Fuse version [Required] =====---------------------------------------
      # Description: The value must be equal or greater than the version stored in fuses to allow loading this
      # container.
      fuse_version: 0
      # ------------------------------------===== Software version [Required] =====-------------------------------------
      # Description: Number used by Privileged Host Boot Companion (PHBC) to select between multiple images with same
      # Fuse version field.
      sw_version: 0
      signing_key: ../_data/keys/ecc384/srk0_ecc384.pem # [Conditionally required], AHAB container signing key, Private key used for sign the container header. Header can be signed by SRK or by image key that was signed by SRK. If an image key is used, it must be the same algorithm and key size as the SRK. In both cases, the referenced SRK must not have been revoked.
      # ================================================================================================================
      #                     == Configuration of AHAB Container images (array of multiple images) ==
      # ================================================================================================================
      # ---------------------------------------===== Image array [Required] =====---------------------------------------
      # Description: Array of image entries.
      images:
        - # ---------------------------------------===== ATF binary [Required] =====----------------------------------------
          # Description: ATF binary file.
          atf: inputs/bl31.bin
          hash_type: sha384
          is_encrypted: true

        - # --------------------------------------===== U-Boot binary [Required] =====--------------------------------------
          # Description: U-Boot binary file.
          uboot:
            inputs/u-boot.bin
            # ----------------------------------===== Images HASH type [Optional] =====-----------------------------------
          # Description: HASH type of image. All images in the container must have the same HASH type.
          # Possible options: <sha256, sha384, sha512, sm3>
          hash_type: sha384
          is_encrypted: true
        # ----------------------------------------------------------------------------------------------------
        #                                == Configuration of AHAB SRK table ==
        # ----------------------------------------------------------------------------------------------------
      srk_table: # [Conditionally required], SRK Table, SRK (Super Root key) table definition.
        srk_array: # [Required], Super Root Key (SRK) table, Table containing the used SRK records. All SRKs must be of the same type. Supported signing algorithms are: RSASSA-PSS or ECDSA. Supported hash algorithms: sha256, sha384, sha512. Supported key sizes/curves: prime256v1, sec384r1, sec512r1, rsa2048, rsa4096. Certificate may be of Certificate Authority.
          - ../_data/keys/ecc384/srk0_ecc384.pub # SRK key, Path to SRK Key file.
          - ../_data/keys/ecc384/srk1_ecc384.pub # SRK key, Path to SRK Key file.
          - ../_data/keys/ecc384/srk2_ecc384.pub # SRK key, Path to SRK Key file.
          - ../_data/keys/ecc384/srk3_ecc384.pub # SRK key, Path to SRK Key file.
      blob:
        key_identifier: 0
        dek_key_size: 128
        dek_key: ../_data/keys/dek_key.txt
        dek_keyblob: ../_data/keys/dek_keyblob.bin
